"""
charts.py
─────────────────────────────────────────────────────────────────────────────
F1 Best Losers Analysis — Visualisations
Reads from CSV outputs generated by f1_analysis.ipynb
Run from project root: python charts.py
Outputs 8 PNG files to ./charts/ directory
─────────────────────────────────────────────────────────────────────────────
"""

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.ticker as mticker
from matplotlib.lines import Line2D
import numpy as np
import os
import warnings
warnings.filterwarnings('ignore')


# ── Config ────────────────────────────────────────────────────────────────────

OUTPUT_DIR = 'charts'
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Colour palette — white background, F1 inspired accents
BG_WHITE     = '#FFFFFF'
BG_PANEL     = '#F7F7F7'
GRID_COLOR   = '#E0E0E0'
TEXT_PRIMARY = '#1A1A1A'
TEXT_MUTED   = '#888888'
ACCENT_RED   = '#E8002D'   # F1 red — Webber spotlight
ACCENT_TEAL  = '#00A896'   # Teal — Hülkenberg inspiration
ACCENT_GOLD  = '#F4A900'   # Gold — wins / highlights
ACCENT_BLUE  = '#1565C0'   # Blue — Ricciardo
ACCENT_GREEN = '#2E7D32'   # Green — Kubica
ACCENT_ORANGE= '#E65100'   # Orange — Trulli
COLOR_BAR    = '#90A4AE'   # Default bar
COLOR_POS    = '#388E3C'   # Positive values
COLOR_NEG    = '#C62828'   # Negative values

SPOTLIGHT   = 'webber'
INSPIRATION = 'hulkenberg'

DISPLAY = {
    'albers': 'Albers', 'albon': 'Albon', 'alguersuari': 'Alguersuari',
    'barrichello': 'Barrichello', 'bottas': 'Bottas', 'bourdais': 'Bourdais',
    'bruno_senna': 'B. Senna', 'buemi': 'Buemi', 'chilton': 'Chilton',
    'coulthard': 'Coulthard', 'ericsson': 'Ericsson', 'fisichella': 'Fisichella',
    'gasly': 'Gasly', 'giovinazzi': 'Giovinazzi', 'glock': 'Glock',
    'grosjean': 'Grosjean', 'gutierrez': 'Gutiérrez', 'heidfeld': 'Heidfeld',
    'hulkenberg': 'Hülkenberg', 'jolyon_palmer': 'J. Palmer',
    'jules_bianchi': 'Bianchi', 'karthikeyan': 'Karthikeyan',
    'kevin_magnussen': 'Magnussen', 'klien': 'Klien', 'kobayashi': 'Kobayashi',
    'kovalainen': 'Kovalainen', 'kubica': 'Kubica', 'kvyat': 'Kvyat',
    'latifi': 'Latifi', 'leclerc': 'Leclerc', 'liuzzi': 'Liuzzi',
    'maldonado': 'Maldonado', 'massa': 'Massa', 'mick_schumacher': 'M. Schumacher',
    'monteiro': 'Monteiro', 'nasr': 'Nasr', 'ocon': 'Ocon', 'perez': 'Pérez',
    'petrov': 'Petrov', 'pic': 'Pic', 'ralf_schumacher': 'R. Schumacher',
    'resta': 'Di Resta', 'ricciardo': 'Ricciardo', 'rosa': 'De la Rosa',
    'russell': 'Russell', 'sainz': 'Sainz', 'sargeant': 'Sargeant',
    'sato': 'Sato', 'stroll': 'Stroll', 'sutil': 'Sutil', 'trulli': 'Trulli',
    'tsunoda': 'Tsunoda', 'vergne': 'Vergne', 'villeneuve': 'Villeneuve',
    'webber': 'Webber', 'wehrlein': 'Wehrlein', 'zhou': 'Zhou',
    'piastri': 'Piastri',
}


def set_style():
    """Apply consistent white theme to all charts."""
    plt.rcParams.update({
        'figure.facecolor':  BG_WHITE,
        'axes.facecolor':    BG_PANEL,
        'axes.edgecolor':    GRID_COLOR,
        'axes.labelcolor':   TEXT_PRIMARY,
        'xtick.color':       TEXT_MUTED,
        'ytick.color':       TEXT_MUTED,
        'text.color':        TEXT_PRIMARY,
        'grid.color':        GRID_COLOR,
        'grid.linewidth':    0.6,
        'font.family':       'monospace',
        'axes.spines.top':   False,
        'axes.spines.right': False,
    })


def save(fig, name):
    path = os.path.join(OUTPUT_DIR, name)
    fig.savefig(path, dpi=180, bbox_inches='tight',
                facecolor=BG_WHITE, edgecolor='none')
    print(f'  ✓ Saved: {path}')
    plt.close(fig)


def add_footer(fig, text='Data: Jolpica F1 API  ·  2005–2025  ·  github.com/costa911/f1-analysis'):
    fig.text(0.01, 0.005, text, fontsize=6.5, color=TEXT_MUTED,
             ha='left', va='bottom', fontfamily='monospace')


# ── Load data ─────────────────────────────────────────────────────────────────

print('Loading CSVs...')
composite     = pd.read_csv('f1_composite_final.csv')
podium_stats  = pd.read_csv('f1_podium_stats.csv')
overperformer = pd.read_csv('f1_overperformer.csv')
teammate      = pd.read_csv('f1_teammate_delta.csv')

composite['display'] = composite['driverId'].map(DISPLAY).fillna(composite['driverId'])
teammate['display']  = teammate['driverId'].map(DISPLAY).fillna(teammate['driverId'])
print(f'  Drivers in composite: {len(composite)}')


# ── CHART 1: Top 20 composite ranking ─────────────────────────────────────────

print('\nBuilding Chart 1: Composite Ranking (Top 20)...')
set_style()

top20 = (
    composite
    .sort_values('composite_score', ascending=False)
    .head(20)
    .sort_values('composite_score', ascending=True)
    .reset_index(drop=True)
)

colors = [
    ACCENT_RED    if d == SPOTLIGHT    else
    ACCENT_TEAL   if d == INSPIRATION  else
    ACCENT_BLUE   if d == 'ricciardo'  else
    ACCENT_GREEN  if d == 'kubica'     else
    ACCENT_ORANGE if d == 'trulli'     else
    COLOR_BAR
    for d in top20['driverId']
]

fig, ax = plt.subplots(figsize=(11, 9))
fig.patch.set_facecolor(BG_WHITE)
ax.set_facecolor(BG_PANEL)

bars = ax.barh(
    top20['display'], top20['composite_score'],
    color=colors, height=0.62,
    edgecolor=BG_WHITE, linewidth=0.8
)

for bar, score in zip(bars, top20['composite_score']):
    ax.text(
        bar.get_width() + 0.006,
        bar.get_y() + bar.get_height() / 2,
        f'{score:.3f}',
        va='center', ha='left',
        fontsize=8, color=TEXT_MUTED, fontfamily='monospace'
    )

ax.axvline(0.5, color=GRID_COLOR, linewidth=1.2, linestyle='--', zorder=0)
ax.text(0.502, -1.2, '0.5 midpoint', fontsize=7, color=TEXT_MUTED)

ids = list(top20['driverId'])

if SPOTLIGHT in ids:
    i = ids.index(SPOTLIGHT)
    x = top20.iloc[i]['composite_score']
    ax.annotate(
        'Data winner\nhighest teammate\ndelta in dataset (+3.57)',
        xy=(x, i), xytext=(x - 0.38, i - 2.8),
        fontsize=7.5, color=ACCENT_RED, fontweight='bold',
        arrowprops=dict(arrowstyle='->', color=ACCENT_RED, lw=1.3)
    )

if INSPIRATION in ids:
    i = ids.index(INSPIRATION)
    x = top20.iloc[i]['composite_score']
    ax.annotate(
        '239 starts · 1 podium\nThe inspiration',
        xy=(x, i), xytext=(x - 0.3, i + 2.2),
        fontsize=7.5, color=ACCENT_TEAL, fontweight='bold',
        arrowprops=dict(arrowstyle='->', color=ACCENT_TEAL, lw=1.3)
    )

ax.set_xlabel(
    'Composite Score  (podium rate + overperformer delta + teammate delta)',
    fontsize=9, color=TEXT_MUTED, labelpad=10
)
ax.set_title(
    'WHO ARE THE BEST LOSERS IN F1?',
    fontsize=15, fontweight='bold', color=TEXT_PRIMARY, pad=16, loc='left'
)
ax.text(0, 1.02, 'Top 20 non-champions by composite score  ·  2005–2025',
        transform=ax.transAxes, fontsize=8.5, color=TEXT_MUTED)
ax.set_xlim(0, 1.05)

legend_els = [
    mpatches.Patch(color=ACCENT_RED,    label='Webber — data winner'),
    mpatches.Patch(color=ACCENT_BLUE,   label='Ricciardo'),
    mpatches.Patch(color=ACCENT_GREEN,  label='Kubica'),
    mpatches.Patch(color=ACCENT_ORANGE, label='Trulli'),
    mpatches.Patch(color=ACCENT_TEAL,   label='Hülkenberg — the inspiration'),
    mpatches.Patch(color=COLOR_BAR,     label='Other drivers'),
]
ax.legend(handles=legend_els, loc='lower right',
          fontsize=8, framealpha=0.9, edgecolor=GRID_COLOR)

ax.tick_params(axis='y', labelsize=9, colors=TEXT_PRIMARY)
add_footer(fig)
plt.tight_layout(rect=[0, 0.02, 1, 1])
save(fig, 'chart1_composite_ranking.png')


# ── CHART 2: Car quality vs overperformance scatter ───────────────────────────

print('Building Chart 2: Car vs Driver scatter...')
set_style()

peak_rank = {
    'webber': 1, 'bottas': 1, 'leclerc': 2, 'russell': 1, 'ricciardo': 2,
    'kubica': 4, 'massa': 2, 'perez': 2, 'sainz': 2, 'grosjean': 5,
    'hulkenberg': 6, 'trulli': 5, 'heidfeld': 4, 'barrichello': 2,
    'kovalainen': 1, 'fisichella': 4, 'coulthard': 3, 'albon': 8,
    'gasly': 3, 'giovinazzi': 8, 'kevin_magnussen': 8, 'stroll': 5,
    'ocon': 5, 'tsunoda': 4, 'kvyat': 3, 'sutil': 6, 'kobayashi': 6,
    'buemi': 7, 'vergne': 6, 'alguersuari': 7, 'glock': 6,
    'ralf_schumacher': 3, 'wehrlein': 9, 'nasr': 8, 'ericsson': 9,
    'gutierrez': 8, 'maldonado': 7, 'petrov': 5, 'liuzzi': 7,
    'klien': 4, 'villeneuve': 8, 'mick_schumacher': 9, 'karthikeyan': 10,
    'monteiro': 10, 'chilton': 10, 'pic': 10, 'latifi': 9, 'sargeant': 9,
    'jolyon_palmer': 7, 'jules_bianchi': 10, 'rosa': 10, 'bourdais': 8,
    'sato': 5, 'bruno_senna': 10, 'albers': 10, 'piastri': 1,
}

scatter_data = composite.copy()
scatter_data['constructor_rank'] = scatter_data['driverId'].map(peak_rank)
scatter_data = scatter_data.dropna(subset=['constructor_rank'])

point_colors = [
    ACCENT_RED    if d == SPOTLIGHT    else
    ACCENT_TEAL   if d == INSPIRATION  else
    ACCENT_BLUE   if d == 'ricciardo'  else
    ACCENT_GREEN  if d == 'kubica'     else
    ACCENT_ORANGE if d == 'trulli'     else
    '#BBBBBB'
    for d in scatter_data['driverId']
]
point_sizes = [
    140 if d in (SPOTLIGHT, INSPIRATION, 'ricciardo', 'kubica', 'trulli') else 40
    for d in scatter_data['driverId']
]

fig, ax = plt.subplots(figsize=(12, 7))
fig.patch.set_facecolor(BG_WHITE)
ax.set_facecolor(BG_PANEL)

med_rank = scatter_data['constructor_rank'].median()
ax.axhline(0,        color=GRID_COLOR, linewidth=0.8, zorder=0)
ax.axvline(med_rank, color=GRID_COLOR, linewidth=0.8, linestyle='--', zorder=0)
ax.fill_between(
    [med_rank, 11], 0,
    scatter_data['overperformer_delta'].max() + 0.1,
    alpha=0.06, color=COLOR_POS, zorder=0
)
ax.text(7.8, scatter_data['overperformer_delta'].max() - 0.05,
        'Weak car,\noverperforming',
        fontsize=7.5, color=COLOR_POS, alpha=0.8)

ax.scatter(
    scatter_data['constructor_rank'],
    scatter_data['overperformer_delta'],
    c=point_colors, s=point_sizes,
    zorder=5, edgecolors=BG_WHITE, linewidth=0.6, alpha=0.9
)

label_drivers = {
    SPOTLIGHT, INSPIRATION, 'kubica', 'trulli', 'ricciardo',
    'albon', 'gasly', 'giovinazzi', 'wehrlein', 'leclerc', 'russell', 'bottas'
}
for _, row in scatter_data.iterrows():
    if row['driverId'] not in label_drivers:
        continue
    color = (
        ACCENT_RED    if row['driverId'] == SPOTLIGHT    else
        ACCENT_TEAL   if row['driverId'] == INSPIRATION  else
        ACCENT_BLUE   if row['driverId'] == 'ricciardo'  else
        ACCENT_GREEN  if row['driverId'] == 'kubica'     else
        ACCENT_ORANGE if row['driverId'] == 'trulli'     else
        TEXT_MUTED
    )
    weight = 'bold' if row['driverId'] in (
        SPOTLIGHT, INSPIRATION, 'ricciardo', 'kubica', 'trulli'
    ) else 'normal'
    dy = 0.05 if row['overperformer_delta'] >= 0 else -0.08
    ax.text(
        row['constructor_rank'] + 0.1,
        row['overperformer_delta'] + dy,
        row['display'], fontsize=7.5,
        color=color, fontweight=weight
    )

ax.set_xlabel('Peak Constructor Rank  (higher = weaker car)',
              fontsize=9, color=TEXT_MUTED, labelpad=10)
ax.set_ylabel('Overperformer Delta\n(positive = finished better than car average)',
              fontsize=9, color=TEXT_MUTED, labelpad=10)
ax.set_title('SEPARATING THE DRIVER FROM THE CAR',
             fontsize=14, fontweight='bold', color=TEXT_PRIMARY, pad=16, loc='left')
ax.text(0, 1.02, 'Car quality vs driver overperformance  ·  2005–2025',
        transform=ax.transAxes, fontsize=8.5, color=TEXT_MUTED)
ax.set_xlim(0, 11)

legend_els = [
    mpatches.Patch(color=ACCENT_RED,    label='Webber'),
    mpatches.Patch(color=ACCENT_BLUE,   label='Ricciardo'),
    mpatches.Patch(color=ACCENT_GREEN,  label='Kubica'),
    mpatches.Patch(color=ACCENT_ORANGE, label='Trulli'),
    mpatches.Patch(color=ACCENT_TEAL,   label='Hülkenberg'),
    mpatches.Patch(color='#BBBBBB',     label='Other drivers'),
]
ax.legend(handles=legend_els, fontsize=8, framealpha=0.9, edgecolor=GRID_COLOR)
add_footer(fig)
plt.tight_layout(rect=[0, 0.02, 1, 1])
save(fig, 'chart2_car_vs_driver.png')


# ── CHART 3: Teammate delta leaderboard ───────────────────────────────────────

print('Building Chart 3: Teammate Delta leaderboard...')
set_style()

top20_tm = (
    teammate
    .sort_values('qual_delta_avg', ascending=False)
    .head(20)
    .sort_values('qual_delta_avg', ascending=True)
    .reset_index(drop=True)
)

colors3 = [
    ACCENT_RED    if d == SPOTLIGHT    else
    ACCENT_TEAL   if d == INSPIRATION  else
    ACCENT_BLUE   if d == 'ricciardo'  else
    ACCENT_GREEN  if d == 'kubica'     else
    ACCENT_ORANGE if d == 'trulli'     else
    COLOR_POS     if v > 0             else
    COLOR_NEG
    for d, v in zip(top20_tm['driverId'], top20_tm['qual_delta_avg'])
]

fig, ax = plt.subplots(figsize=(11, 8.5))
fig.patch.set_facecolor(BG_WHITE)
ax.set_facecolor(BG_PANEL)

bars = ax.barh(
    top20_tm['display'], top20_tm['qual_delta_avg'],
    color=colors3, height=0.62,
    edgecolor=BG_WHITE, linewidth=0.8
)

for bar, val in zip(bars, top20_tm['qual_delta_avg']):
    x  = bar.get_width() + 0.05 if val >= 0 else bar.get_width() - 0.05
    ha = 'left'                  if val >= 0 else 'right'
    ax.text(x, bar.get_y() + bar.get_height() / 2,
            f'{val:+.2f}', va='center', ha=ha,
            fontsize=8.5, color=TEXT_MUTED, fontfamily='monospace')

ax.axvline(0, color=TEXT_MUTED, linewidth=0.8)
ax.set_xlabel('Avg Qualifying Gap vs Teammate  (positive = qualified ahead)',
              fontsize=9, color=TEXT_MUTED, labelpad=10)
ax.set_title('THE CAR-NEUTRAL TALENT RANKING',
             fontsize=14, fontweight='bold', color=TEXT_PRIMARY, pad=16, loc='left')
ax.text(0, 1.02,
        'Teammate delta leaderboard — same car, same weekend  ·  Top 20  ·  2005–2025',
        transform=ax.transAxes, fontsize=8.5, color=TEXT_MUTED)

legend_els = [
    mpatches.Patch(color=ACCENT_RED,    label='Webber'),
    mpatches.Patch(color=ACCENT_BLUE,   label='Ricciardo'),
    mpatches.Patch(color=ACCENT_GREEN,  label='Kubica'),
    mpatches.Patch(color=ACCENT_ORANGE, label='Trulli'),
    mpatches.Patch(color=ACCENT_TEAL,   label='Hülkenberg'),
    mpatches.Patch(color=COLOR_POS,     label='Ahead of teammate'),
    mpatches.Patch(color=COLOR_NEG,     label='Behind teammate'),
]
ax.legend(handles=legend_els, loc='lower right',
          fontsize=8, framealpha=0.9, edgecolor=GRID_COLOR)

ax.tick_params(axis='y', labelsize=9, colors=TEXT_PRIMARY)
add_footer(fig)
plt.tight_layout(rect=[0, 0.02, 1, 1])
save(fig, 'chart3_teammate_delta.png')


# ── CHART 4: Webber career spotlight ─────────────────────────────────────────

print('Building Chart 4: Webber career spotlight...')
set_style()

webber_seasons = pd.DataFrame({
    'season':          [2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013],
    'points':          [36,   7,    10,   21,   51.5, 242,  258,  179,  199],
    'driver_pos':      [10,   14,   12,   11,   4,    2,    3,    3,    3],
    'constructor_pos': [7,    5,    3,    3,    2,    1,    1,    2,    1],
    'wins':            [0,    0,    0,    0,    1,    4,    1,    2,    2],
})

fig, ax1 = plt.subplots(figsize=(11, 6))
fig.patch.set_facecolor(BG_WHITE)
ax1.set_facecolor(BG_PANEL)
ax2 = ax1.twinx()
ax2.set_facecolor(BG_PANEL)

ax1.bar(webber_seasons['season'], webber_seasons['points'],
        color=ACCENT_RED, alpha=0.75, width=0.5, label='Points scored', zorder=3)

for _, row in webber_seasons[webber_seasons['wins'] > 0].iterrows():
    ax1.text(row['season'], row['points'] + 6,
             '★' * int(row['wins']),
             ha='center', fontsize=9, color=ACCENT_GOLD, zorder=4)

ax2.plot(webber_seasons['season'], webber_seasons['driver_pos'],
         color=TEXT_PRIMARY, marker='o', linewidth=2, markersize=7,
         label='Webber championship position', zorder=5)
ax2.plot(webber_seasons['season'], webber_seasons['constructor_pos'],
         color=TEXT_MUTED, marker='s', linewidth=1.5, linestyle='--',
         markersize=6, label='Constructor position', zorder=4)

ax1.axvspan(2009.7, 2010.3, alpha=0.07, color=ACCENT_GOLD, zorder=0)
ax1.text(2010, 255, '2010 — Championship\nlost in Abu Dhabi',
         ha='center', fontsize=7.5, color=ACCENT_GOLD)
ax1.axvline(2008.5, color=GRID_COLOR, linestyle=':', linewidth=1)
ax1.text(2008.6, 220, '→ Joins Red Bull', fontsize=7.5, color=TEXT_MUTED)

ax1.set_xlabel('Season', fontsize=9, color=TEXT_MUTED, labelpad=10)
ax1.set_ylabel('Championship Points', fontsize=9, color=ACCENT_RED, labelpad=10)
ax2.set_ylabel('Championship Position  (lower = better)',
               fontsize=9, color=TEXT_MUTED, labelpad=10)
ax2.invert_yaxis()
ax2.set_ylim(16, 0.5)
ax1.set_title('MARK WEBBER — THE DATA WINNER',
              fontsize=14, fontweight='bold', color=TEXT_PRIMARY, pad=16, loc='left')
ax1.text(0, 1.02, 'Season-by-season points vs championship position  ·  ★ = race win',
         transform=ax1.transAxes, fontsize=8.5, color=TEXT_MUTED)
ax1.set_xticks(webber_seasons['season'])

lines1, labels1 = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
ax1.legend(lines1 + lines2, labels1 + labels2,
           fontsize=8, framealpha=0.9, edgecolor=GRID_COLOR, loc='upper left')

for spine in ['top']:
    ax1.spines[spine].set_visible(False)
    ax2.spines[spine].set_visible(False)

add_footer(fig)
plt.tight_layout(rect=[0, 0.02, 1, 1])
save(fig, 'chart4_webber_spotlight.png')


# ── CHART 5: Kubica career spotlight ─────────────────────────────────────────

print('Building Chart 5: Kubica career spotlight...')
set_style()

kubica_seasons = pd.DataFrame({
    'season':          [2006, 2007, 2008, 2009, 2010, 2019],
    'points':          [6,    39,   75,   17,   8,    1],
    'driver_pos':      [16,   6,    4,    9,    15,   19],
    'constructor_pos': [8,    5,    3,    6,    6,    9],
    'wins':            [0,    0,    1,    0,    0,    0],
})

fig, ax1 = plt.subplots(figsize=(11, 6))
fig.patch.set_facecolor(BG_WHITE)
ax1.set_facecolor(BG_PANEL)
ax2 = ax1.twinx()
ax2.set_facecolor(BG_PANEL)

ax1.bar(kubica_seasons['season'], kubica_seasons['points'],
        color=ACCENT_GREEN, alpha=0.75, width=0.5, label='Points scored', zorder=3)

for _, row in kubica_seasons[kubica_seasons['wins'] > 0].iterrows():
    ax1.text(row['season'], row['points'] + 3,
             '★', ha='center', fontsize=11, color=ACCENT_GOLD, zorder=4)
    ax1.annotate('Canadian GP\nFirst Polish F1 winner',
                 xy=(row['season'], row['points']),
                 xytext=(row['season'] + 0.5, row['points'] - 15),
                 fontsize=7.5, color=ACCENT_GREEN,
                 arrowprops=dict(arrowstyle='->', color=ACCENT_GREEN, lw=1.2))

ax2.plot(kubica_seasons['season'], kubica_seasons['driver_pos'],
         color=TEXT_PRIMARY, marker='o', linewidth=2, markersize=7,
         label='Kubica championship position', zorder=5)
ax2.plot(kubica_seasons['season'], kubica_seasons['constructor_pos'],
         color=TEXT_MUTED, marker='s', linewidth=1.5, linestyle='--',
         markersize=6, label='Constructor position', zorder=4)

ax1.axvspan(2010.4, 2018.6, alpha=0.04, color=COLOR_NEG, zorder=0)
ax1.text(2014.5, 65, '2011 rally accident\n— 8 years away from F1 —',
         ha='center', fontsize=8, color=COLOR_NEG, alpha=0.8)
ax1.axvline(2010.4, color=COLOR_NEG, linestyle='--', linewidth=1, alpha=0.4)
ax1.axvline(2018.6, color=COLOR_NEG, linestyle='--', linewidth=1, alpha=0.4)

ax1.set_xlabel('Season', fontsize=9, color=TEXT_MUTED, labelpad=10)
ax1.set_ylabel('Championship Points', fontsize=9, color=ACCENT_GREEN, labelpad=10)
ax2.set_ylabel('Championship Position  (lower = better)',
               fontsize=9, color=TEXT_MUTED, labelpad=10)
ax2.invert_yaxis()
ax2.set_ylim(22, 0.5)
ax1.set_title('ROBERT KUBICA — THE WHAT-IF',
              fontsize=14, fontweight='bold', color=TEXT_PRIMARY, pad=16, loc='left')
ax1.text(0, 1.02,
         'Career cut short by a 2011 rally accident at the height of his powers  ·  ★ = race win',
         transform=ax1.transAxes, fontsize=8.5, color=TEXT_MUTED)
ax1.set_xticks(kubica_seasons['season'])
ax1.set_xlim(2005.5, 2019.5)

lines1, labels1 = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
ax1.legend(lines1 + lines2, labels1 + labels2,
           fontsize=8, framealpha=0.9, edgecolor=GRID_COLOR, loc='upper right')

add_footer(fig)
plt.tight_layout(rect=[0, 0.02, 1, 1])
save(fig, 'chart5_kubica_spotlight.png')


# ── CHART 6: Ricciardo career spotlight ──────────────────────────────────────

print('Building Chart 6: Ricciardo career spotlight...')
set_style()

ricciardo_seasons = pd.DataFrame({
    'season':          [2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022],
    'points':          [10,   19,   238,  92,   256,  200,  170,  54,   119,  115,  37],
    'driver_pos':      [18,   15,   3,    8,    3,    5,    6,    9,    5,    8,    11],
    'constructor_pos': [9,    6,    2,    2,    2,    4,    4,    5,    3,    3,    5],
    'wins':            [0,    0,    3,    1,    2,    1,    2,    0,    1,    1,    0],
})

fig, ax1 = plt.subplots(figsize=(12, 6))
fig.patch.set_facecolor(BG_WHITE)
ax1.set_facecolor(BG_PANEL)
ax2 = ax1.twinx()
ax2.set_facecolor(BG_PANEL)

ax1.bar(ricciardo_seasons['season'], ricciardo_seasons['points'],
        color=ACCENT_BLUE, alpha=0.75, width=0.5, label='Points scored', zorder=3)

for _, row in ricciardo_seasons[ricciardo_seasons['wins'] > 0].iterrows():
    ax1.text(row['season'], row['points'] + 6,
             '★' * int(row['wins']),
             ha='center', fontsize=9, color=ACCENT_GOLD, zorder=4)

ax2.plot(ricciardo_seasons['season'], ricciardo_seasons['driver_pos'],
         color=TEXT_PRIMARY, marker='o', linewidth=2, markersize=7,
         label='Ricciardo championship position', zorder=5)
ax2.plot(ricciardo_seasons['season'], ricciardo_seasons['constructor_pos'],
         color=TEXT_MUTED, marker='s', linewidth=1.5, linestyle='--',
         markersize=6, label='Constructor position', zorder=4)

ax1.axvspan(2013.7, 2014.3, alpha=0.08, color=ACCENT_GOLD, zorder=0)
ax1.text(2014, 248, '2014 — Beat Vettel\nin the same car',
         ha='center', fontsize=7.5, color=ACCENT_GOLD)

for x, label in [(2013.5, 'Red Bull'), (2016.5, 'Renault'), (2020.5, 'McLaren')]:
    ax1.axvline(x, color=GRID_COLOR, linestyle=':', linewidth=1)
    ax1.text(x + 0.08, 235, f'→ {label}', fontsize=6.5, color=TEXT_MUTED)

ax1.set_xlabel('Season', fontsize=9, color=TEXT_MUTED, labelpad=10)
ax1.set_ylabel('Championship Points', fontsize=9, color=ACCENT_BLUE, labelpad=10)
ax2.set_ylabel('Championship Position  (lower = better)',
               fontsize=9, color=TEXT_MUTED, labelpad=10)
ax2.invert_yaxis()
ax2.set_ylim(20, 0.5)
ax1.set_title('DANIEL RICCIARDO — THE NEARLY-MAN WHO PROVED IT',
              fontsize=14, fontweight='bold', color=TEXT_PRIMARY, pad=16, loc='left')
ax1.text(0, 1.02,
         'Peak in 2014: outqualified and outscored Vettel in the same Red Bull  ·  ★ = race win',
         transform=ax1.transAxes, fontsize=8.5, color=TEXT_MUTED)
ax1.set_xticks(ricciardo_seasons['season'])

lines1, labels1 = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
ax1.legend(lines1 + lines2, labels1 + labels2,
           fontsize=8, framealpha=0.9, edgecolor=GRID_COLOR, loc='upper right')

add_footer(fig)
plt.tight_layout(rect=[0, 0.02, 1, 1])
save(fig, 'chart6_ricciardo_spotlight.png')


# ── CHART 7: Trulli career spotlight ─────────────────────────────────────────

print('Building Chart 7: Trulli career spotlight...')
set_style()

trulli_seasons = pd.DataFrame({
    'season':          [2005, 2006, 2007, 2008, 2009],
    'points':          [43,   15,   8,    31,   32.5],
    'driver_pos':      [7,    12,   15,   9,    8],
    'constructor_pos': [4,    6,    6,    5,    5],
})

fig, ax1 = plt.subplots(figsize=(10, 6))
fig.patch.set_facecolor(BG_WHITE)
ax1.set_facecolor(BG_PANEL)
ax2 = ax1.twinx()
ax2.set_facecolor(BG_PANEL)

ax1.bar(trulli_seasons['season'], trulli_seasons['points'],
        color=ACCENT_ORANGE, alpha=0.75, width=0.4, label='Points scored', zorder=3)

ax2.plot(trulli_seasons['season'], trulli_seasons['driver_pos'],
         color=TEXT_PRIMARY, marker='o', linewidth=2, markersize=7,
         label='Trulli championship position', zorder=5)
ax2.plot(trulli_seasons['season'], trulli_seasons['constructor_pos'],
         color=TEXT_MUTED, marker='s', linewidth=1.5, linestyle='--',
         markersize=6, label='Toyota constructor position', zorder=4)

ax1.annotate(
    '"The Trulli Train"\nElite over one lap\nhard to pass on race day',
    xy=(2005, 43), xytext=(2006.3, 36),
    fontsize=7.5, color=ACCENT_ORANGE,
    arrowprops=dict(arrowstyle='->', color=ACCENT_ORANGE, lw=1.2)
)

ax1.set_xlabel('Season', fontsize=9, color=TEXT_MUTED, labelpad=10)
ax1.set_ylabel('Championship Points', fontsize=9, color=ACCENT_ORANGE, labelpad=10)
ax2.set_ylabel('Championship Position  (lower = better)',
               fontsize=9, color=TEXT_MUTED, labelpad=10)
ax2.invert_yaxis()
ax2.set_ylim(18, 0.5)
ax1.set_title('JARNO TRULLI — THE QUALIFYING MAESTRO',
              fontsize=14, fontweight='bold', color=TEXT_PRIMARY, pad=16, loc='left')
ax1.text(0, 1.02,
         'Consistently placed Toyota above where the car deserved  ·  Toyota never won a race',
         transform=ax1.transAxes, fontsize=8.5, color=TEXT_MUTED)
ax1.set_xticks(trulli_seasons['season'])

lines1, labels1 = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
ax1.legend(lines1 + lines2, labels1 + labels2,
           fontsize=8, framealpha=0.9, edgecolor=GRID_COLOR, loc='upper right')

add_footer(fig)
plt.tight_layout(rect=[0, 0.02, 1, 1])
save(fig, 'chart7_trulli_spotlight.png')


# ── CHART 8: Hülkenberg career spotlight ─────────────────────────────────────

print('Building Chart 8: Hülkenberg career spotlight...')
set_style()

hulk_seasons = pd.DataFrame({
    'season':          [2010, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2022, 2023, 2024, 2025],
    'points':          [22,   63,   51,   96,   58,   72,   43,   69,   37,   12,   55,   31,   51],
    'driver_pos':      [14,   11,   10,   8,    10,   8,    10,   7,    14,   17,   12,   10,   11],
    'constructor_pos': [6,    5,    6,    6,    5,    4,    6,    4,    5,    8,    8,    10,   8],
    'podiums':         [0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1],
})

fig, ax1 = plt.subplots(figsize=(13, 6))
fig.patch.set_facecolor(BG_WHITE)
ax1.set_facecolor(BG_PANEL)
ax2 = ax1.twinx()
ax2.set_facecolor(BG_PANEL)

bar_colors = [ACCENT_TEAL if p > 0 else COLOR_BAR for p in hulk_seasons['podiums']]
ax1.bar(hulk_seasons['season'], hulk_seasons['points'],
        color=bar_colors, alpha=0.8, width=0.5, label='Points scored', zorder=3)

podium_row = hulk_seasons[hulk_seasons['podiums'] > 0].iloc[0]
ax1.text(podium_row['season'], podium_row['points'] + 2.5,
         '🏆', ha='center', fontsize=12, zorder=4)
ax1.annotate(
    '2025 British GP\nP19 → P3 in the rain\n239th start',
    xy=(2025, podium_row['points']),
    xytext=(2023.0, 46),
    fontsize=7.5, color=ACCENT_TEAL, fontweight='bold',
    arrowprops=dict(arrowstyle='->', color=ACCENT_TEAL, lw=1.3)
)

ax1.axvspan(2010.4, 2011.6, alpha=0.05, color=TEXT_MUTED, zorder=0)
ax1.text(2011, 78, 'No seat\n2011', ha='center', fontsize=6.5, color=TEXT_MUTED)
ax1.axvspan(2019.4, 2021.6, alpha=0.05, color=TEXT_MUTED, zorder=0)
ax1.text(2020.5, 78, 'No full-time\nseat 2020–21',
         ha='center', fontsize=6.5, color=TEXT_MUTED)

ax2.plot(hulk_seasons['season'], hulk_seasons['driver_pos'],
         color=TEXT_PRIMARY, marker='o', linewidth=2, markersize=6,
         label='Championship position', zorder=5)

ax1.set_xlabel('Season', fontsize=9, color=TEXT_MUTED, labelpad=10)
ax1.set_ylabel('Championship Points', fontsize=9, color=ACCENT_TEAL, labelpad=10)
ax2.set_ylabel('Championship Position  (lower = better)',
               fontsize=9, color=TEXT_MUTED, labelpad=10)
ax2.invert_yaxis()
ax2.set_ylim(22, 0.5)
ax1.set_title('NICO HÜLKENBERG — WHERE THIS ALL STARTED',
              fontsize=14, fontweight='bold', color=TEXT_PRIMARY, pad=16, loc='left')
ax1.text(0, 1.02,
         '239 starts  ·  1 podium  ·  The longest wait in F1 history',
         transform=ax1.transAxes, fontsize=8.5, color=TEXT_MUTED)
ax1.set_xticks(hulk_seasons['season'])
plt.setp(ax1.xaxis.get_majorticklabels(), rotation=45, ha='right')

lines1, labels1 = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
ax1.legend(lines1 + lines2, labels1 + labels2,
           fontsize=8, framealpha=0.9, edgecolor=GRID_COLOR, loc='upper right')

add_footer(fig)
plt.tight_layout(rect=[0, 0.02, 1, 1])
save(fig, 'chart8_hulkenberg_spotlight.png')


# ── Done ──────────────────────────────────────────────────────────────────────

print(f'\n✅ All 8 charts saved to ./{OUTPUT_DIR}/')
print('   chart1_composite_ranking.png    — Top 20 overall ranking')
print('   chart2_car_vs_driver.png        — Car quality vs overperformance')
print('   chart3_teammate_delta.png       — Teammate delta leaderboard')
print('   chart4_webber_spotlight.png     — Webber career')
print('   chart5_kubica_spotlight.png     — Kubica career')
print('   chart6_ricciardo_spotlight.png  — Ricciardo career')
print('   chart7_trulli_spotlight.png     — Trulli career')
print('   chart8_hulkenberg_spotlight.png — Hülkenberg career')
